name: MysteriaEssentials
version: 1.0.0
api-version: 1.18
description: Fuegt einige standard Commands hinzu
main: net.mysteria.essentials.main.Main
author: IceCream

commands:
  gm:
     description: Setzt dich in den GameMode deiner Wahl
     usage: /gm <GameMode(0|1|2|3)>
     aliases: [gmode]
  vanish:
     description: Macht die unsichtbar und loescht deinen Namen von der TabList
     usage: /vanish
     aliases: [v]
  invsee:
     description: Zeigt dir das Inventar des angegebenen Spielers
     usage: /invsee <Spieler>
     aliases: [showinventory]
  spectate:
     description: Laesst dich in die sicht eines anderen Spielers schluepfen
     usage: /spectate <Spieler>
     aliases: [sp]
  info:
     description: Zeigt dir generelle Infos ueber den Spieler
     usage: /info <Spieler>
     aliases: [playerinfo, showinfo]
